# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamain',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
